# Generated by Django 5.0.6 on 2024-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_medical_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="medical",
            name="entities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="medical",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
